jobs:
  sca:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: codeScan
      uses: layotto/alipay-cloud-devops-codescan@main
      with:
        parent_uid: ${{ secrets.ALI_PID }}
        private_key: ${{ secrets.ALI_PK }}
        scan_type: sca
  stc:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: codeScan
      uses: layotto/alipay-cloud-devops-codescan@main
      with:
        parent_uid: ${{ secrets.ALI_PID }}
        private_key: ${{ secrets.ALI_PK }}
        scan_type: stc
name: Alipay Cloud Devops Codescan
on:
  repository_dispatch:
    types: trigger-ga___cloud_code_scan.yml
