jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw clean install -Pci-install -B -U -e && bash ./tools/check_format.sh
    - continue-on-error: true
      name: Test with Maven
      run: ./mvnw package -Pci-test
    - continue-on-error: true
      name: Codecov
      uses: codecov/codecov-action@v1
name: build
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
